### ISSUE TITLE
Comparing new cases in daily repost with official data

### ISSUE THREAD

**Issue by daviddetorres** [pvieito/Radar-STATS#1]
Hi, 
I've been diving a little bit in the data, and I was seeing that in the [current report](../blob/master/Notebooks/RadarCOVID-Report/Current/RadarCOVID-Report.ipynb) the plot resulting from this line: 
```
In [7]:
confirmed_df[["new_cases", "rolling_mean_new_cases"]].plot()
```

Is showing the same shape of the curve than the official data, but not the same scale (sample [here](https://google.com/covid19-map/?hl=en-ES&mid=/m/06mkj)). 

While in the official data the peak in March was on 9.16k, in the report shows slightly below 20k. The same seems to happen along the curve, showing double the cases than the official data.

**Comment by pvieito** [comment]
@daviddetorres Oh, thanks! The API returns both the national and regional results, and after I did some tests I left commented the part which should filter the dataset to only contain the national results so the data was duplicated. Fixed on [347aeb](https://github.com/pvieito/RadarCOVID-Report/commit/347aeb5744b85b85824c32d12179a3e5c8f1f741).

Thanks a lot!

**Comment by daviddetorres** [comment]
Wow, great support! Thanks a lot for the head up! 👍🏼
