### ISSUE TITLE
Modify JSON filename to remove any COVID reference

### ISSUE THREAD

**Issue by jorgej-ramos** [pvieito/Radar-STATS#3]
Not an issue,but:

Due to the strict regulations of Apple and Google to upload applications to their stores that include references to COVID19, it would be good to omit the word **COVID** from the file name:

`/Data/Resources/Current/RadarCOVID-Report-Summary-Results.json`

At least while `RadarSTATSKit` is implemented and to be able to pass the review.
I suggest something like:
`/Data/Resources/Current/Report-Summary-Results.json`

**Comment by pvieito** [comment]
This should be an implementation detail that it is not surfaced on the app UI to the user so I don't think it is worth changing nor should it be in the scope of the App Store review 🤔

**Comment by jorgej-ramos** [comment]
I'll give it a try. The obsession with Apple regulations blinds me a bit.
